jobs:
  build:
    docker:
      - image: tmyt/cimg-golang-mingw
    environment:
      GOOS: windows
      GOARCH: arm64
      ENABLE_CGO: 1
      CC: aarch64-w64-mingw32-gcc
    steps:
      - checkout
      - run:
          name: sync submodules
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: make binary
          command: make cloudflared
          working_directory: cloudflared
      - store_artifacts:
          path: cloudflared/cloudflared.exe
          destination: cloudflared-windows-arm64.exe
